// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
// GENERATED by rhonet/merkle.py - do not edit
library Fixture {
    bytes32 constant ROOT = 0x65e538c40e0ede805ebb11b1046bb465980ee8011d1581c0e60706ab11a3ed41;
    uint256 constant TOTAL = 105000000;
    function leaf0() internal pure returns (address a, uint256 s, bytes32[] memory p) {
        a = 0x0000000000000000000000000000000000000001; s = 7000000;
        p = new bytes32[](3);
        p[0] = 0xb30853c459e06424a61ea399cf15be1ae1e3c7ac22cc9072291bc10d67f3a750;
        p[1] = 0xcdba985cf45cd44c9f4f6ca9976402a2869e543e8ebcc093725de921836602cf;
        p[2] = 0xcfafce6e1bc413b3f3c8ead38ce5e689505cb18f2d30a44aea29205a32b64889;
    }
    function leaf1() internal pure returns (address a, uint256 s, bytes32[] memory p) {
        a = 0x0000000000000000000000000000000000000002; s = 14000000;
        p = new bytes32[](3);
        p[0] = 0x2bcd67b1691a6e86b239de7ed81b65e373390e61e4eadd59c6c9caf69d989574;
        p[1] = 0xcdba985cf45cd44c9f4f6ca9976402a2869e543e8ebcc093725de921836602cf;
        p[2] = 0xcfafce6e1bc413b3f3c8ead38ce5e689505cb18f2d30a44aea29205a32b64889;
    }
    function leaf2() internal pure returns (address a, uint256 s, bytes32[] memory p) {
        a = 0x0000000000000000000000000000000000000003; s = 21000000;
        p = new bytes32[](3);
        p[0] = 0x58b8d012889efb138a64fbe2b418f1fc152215750ff373c94173e4ea336cbb5a;
        p[1] = 0x6ca589bb261bf787166c6a88da1731f141453595b07a5a2c1d33bf06159fc3d4;
        p[2] = 0xcfafce6e1bc413b3f3c8ead38ce5e689505cb18f2d30a44aea29205a32b64889;
    }
    function leaf3() internal pure returns (address a, uint256 s, bytes32[] memory p) {
        a = 0x0000000000000000000000000000000000000004; s = 28000000;
        p = new bytes32[](3);
        p[0] = 0x44608fe87fd072de703ccd9d76822e43f76bde99f34a3e32d62c9e168e4ec457;
        p[1] = 0x6ca589bb261bf787166c6a88da1731f141453595b07a5a2c1d33bf06159fc3d4;
        p[2] = 0xcfafce6e1bc413b3f3c8ead38ce5e689505cb18f2d30a44aea29205a32b64889;
    }
    function leaf4() internal pure returns (address a, uint256 s, bytes32[] memory p) {
        a = 0x0000000000000000000000000000000000000005; s = 35000000;
        p = new bytes32[](1);
        p[0] = 0x9433c90876088f757fb49f6c9909e9731ed80498cca75b94e34f4effe45477f4;
    }
}
