"""Generate spec/vectors.json: the conformance vectors for an independent client.

Everything a second implementation has to reproduce byte for byte is pinned here:
the primitive encodings, the walk table, PRF-derived starts, the step function, the
checkpoint chain and its Merkle commitment, a segment opening, the exact bytes of
every signed message type, and the payment Merkle tree.

    python -m tools.gen_vectors            # write spec/vectors.json
    python -m tools.gen_vectors --check    # fail if the file is out of date

The vectors are generated from the reference implementation, and tests/test_vectors.py
checks the reference implementation back against the file. That loop catches an
accidental change of the wire format: any edit that moves a byte moves a vector, and
a moved vector has to be an explicit, reviewed commit.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from rhonet import ec, merkle

ROUND = "rounds/r32.json"
# A fixed, deliberately public test key. Never use it for anything real.
TEST_SEED = bytes([42]) * 32
TRACE_STEPS = 32
PAYOUT = "0x" + "ab" * 20


def root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def hx(b: bytes) -> str:
    return b.hex()


def build() -> dict:
    key = Ed25519PrivateKey.from_private_bytes(TEST_SEED)
    pub = key.public_key().public_bytes_raw()
    pubkey = pub.hex()
    round_path = os.path.join(root(), ROUND)
    with open(round_path) as f:
        round_json = json.load(f)
    spec = ec.RoundSpec.load(round_path)
    table = ec.walk_table(spec)

    out: dict = {
        "format": "rhonet-vectors-v1",
        "wire": ec.WIRE_MAGIC.decode("latin-1"),
        "note": "Generated by tools/gen_vectors.py. See docs/PROTOCOL.md.",
        "round": round_json,
        "identity": {"ed25519_seed": hx(TEST_SEED), "pubkey": pubkey, "payout": PAYOUT},
    }

    # --- primitives ----------------------------------------------------------
    out["uvarint"] = [{"n": n, "hex": hx(ec.uvarint(n))}
                      for n in (0, 1, 127, 128, 255, 300, 16383, 16384, 1 << 32)]
    out["uint_bytes"] = [{"n": n, "hex": hx(ec.uint_bytes(n))}
                         for n in (0, 1, 255, 256, 65535, 1 << 64, spec.curve.p - 1)]
    out["encode"] = [
        {"domain": "rhonet/test-v1", "fields": [], "hex": hx(ec.encode("rhonet/test-v1", []))},
        {"domain": "rhonet/test-v1", "fields": [{"uint": 0}],
         "hex": hx(ec.encode("rhonet/test-v1", [0]))},
        {"domain": "rhonet/test-v1",
         "fields": [{"text": "abc"}, {"uint": 300}, {"bytes": "00ff"}],
         "hex": hx(ec.encode("rhonet/test-v1", ["abc", 300, bytes.fromhex("00ff")]))},
        {"domain": "rhonet/test-v1",
         "fields": [{"list": [{"uint": 1}, {"uint": 2}]}, {"list": []}],
         "hex": hx(ec.encode("rhonet/test-v1", [[1, 2], []]))},
    ]
    out["hash"] = [
        {"parts": [{"text": "abc"}], "hex": hx(ec.H("abc"))},
        {"parts": [{"text": "a"}, {"uint": 1}, {"bytes": "ff"}],
         "hex": hx(ec.H("a", 1, bytes.fromhex("ff")))},
    ]

    # --- walk table ----------------------------------------------------------
    out["walk_table"] = {
        "r": spec.r,
        "entries_head": [list(e) for e in table[:4]],
        "entries_tail": [list(e) for e in table[-2:]],
        "digest": hx(ec.H("vectors-table", ec.canonical([list(e) for e in table]))),
    }

    # --- PRF starts ----------------------------------------------------------
    starts = []
    for t in (0, 1, 7, 1000, (1 << 40) + 3):
        a0, b0, P0 = ec.derive_start(spec, pubkey, t)
        starts.append({"t": t, "a0": a0, "b0": b0, "x": P0[0], "y": P0[1]})
    out["starts"] = starts
    a0, b0, P0 = ec.derive_start(spec, pubkey, 0, tag="ticket")
    out["ticket_start"] = {"nonce": 0, "a0": a0, "b0": b0, "x": P0[0], "y": P0[1]}

    # --- step function, one state per step -----------------------------------
    a, b, P = ec.derive_start(spec, pubkey, 0)
    trace = [[a, b, P[0], P[1]]]
    for _ in range(TRACE_STEPS):
        a, b, P = ec.replay(spec, table, a, b, P, 1)
        trace.append([a, b, P[0], P[1]])
    out["trace"] = {"t": 0, "steps": TRACE_STEPS, "states": trace,
                    "branch_indices": [ec.branch_index(s[2], spec.r, spec.w) for s in trace[:-1]]}

    # --- one full walk to a distinguished point, with its checkpoint chain ----
    # Take the first walk long enough to exercise a checkpoint tree of real depth,
    # so the openings pin a multi-level Merkle proof rather than a two-leaf one.
    counter = iter(range(1 << 16))
    walker = ec.BatchWalker(spec, table, pubkey, 1, counter.__next__)
    dp = None
    while dp is None:
        for candidate in walker.step():
            if candidate["steps"] >= 128:
                dp = candidate
    t = dp["t"]
    chain = walker.checkpoints[t]
    segments = (dp["steps"] + (1 << spec.v) - 1) >> spec.v
    out["dp"] = {k: dp[k] for k in ("t", "steps", "x", "y", "a", "b", "checkpoint_root")}
    out["checkpoints"] = {"v": spec.v, "segment_length": 1 << spec.v, "segments": segments,
                          "count": len(chain), "chain": [list(c) for c in chain],
                          "root": ec.checkpoint_root(chain)}
    openings = []
    for segment in (0, segments // 2, segments - 1):
        opening = ec.checkpoint_opening(chain, segment)
        ok, work = ec.verify_segment(spec, table, pubkey, dp, segment, opening)
        assert ok, f"reference opening for segment {segment} does not verify"
        openings.append({"segment": segment, "opening": opening, "replayed_steps": work})
    out["openings"] = openings

    # --- signed messages -----------------------------------------------------
    ticket = ec.ticket_solve(spec, table, pubkey)
    assert ticket is not None
    out["ticket"] = ticket
    bodies = [
        ("admission", {"round_id": spec.round_id, "pubkey": pubkey, "payout_addr": PAYOUT,
                       "ticket": ticket, "epoch": 3, "seq": 1,
                       "device": "Apple M4 Pro"}),
        ("submission", {"round_id": spec.round_id, "pubkey": pubkey, "epoch": 3, "seq": 2,
                        "steps_done": 123456, "abandoned": 2,
                        "dps": [{k: dp[k] for k in ("t", "steps", "x", "y", "a", "b",
                                                    "checkpoint_root")}]}),
        ("submission_empty", {"round_id": spec.round_id, "pubkey": pubkey, "epoch": 3,
                              "seq": 3, "steps_done": 0, "abandoned": 0, "dps": []}),
        ("opening", {"round_id": spec.round_id, "pubkey": pubkey, "audit_epoch": 3,
                     "t": t, "opening": dict(openings[0]["opening"], segment=0),
                     "epoch": 3, "seq": 4}),
        ("rotate", {"round_id": spec.round_id, "pubkey": pubkey,
                    "payout_addr": "0x" + "cd" * 20, "epoch": 3, "seq": 5}),
    ]
    signed = []
    for name, body in bodies:
        message = ec.sign_bytes_for(body)
        signed.append({"name": name, "body": body, "signed_hex": hx(message),
                       "sig": hx(key.sign(message))})
    contributor = ec.sign_bytes_contributor("octocat", pub,
                                            bytes.fromhex(PAYOUT.removeprefix("0x")))
    signed.append({"name": "contributor",
                   "body": {"github": "octocat", "pubkey": pubkey, "payout": PAYOUT},
                   "signed_hex": hx(contributor), "sig": hx(key.sign(contributor))})
    out["signed"] = signed

    # --- payment Merkle tree -------------------------------------------------
    rows = [("0x" + "11" * 20, 1 << 30), ("0x" + "22" * 20, 3 << 30), ("0x" + "33" * 20, 7)]
    leaves = [merkle.leaf_hash(a_, s) for a_, s in rows]
    m_root, layers = merkle.build(leaves)
    out["payment_merkle"] = {
        "leaves": [{"addr": a_, "steps": s, "hash": hx(h)} for (a_, s), h in zip(rows, leaves)],
        "root": hx(m_root),
        "proofs": [[hx(p) for p in merkle.proof(layers, i)] for i in range(len(rows))],
        "empty_root": hx(merkle.build([])[0]),
    }
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit nonzero if spec/vectors.json differs from a fresh build")
    ap.add_argument("--out", default=os.path.join(root(), "spec", "vectors.json"))
    args = ap.parse_args(argv)
    text = json.dumps(build(), indent=2, sort_keys=True) + "\n"
    if args.check:
        try:
            with open(args.out) as f:
                current = f.read()
        except OSError:
            print(f"{args.out} is missing; run python -m tools.gen_vectors", file=sys.stderr)
            return 1
        if current != text:
            print(f"{args.out} is out of date. If the wire format changed on purpose, "
                  f"run python -m tools.gen_vectors and commit the result.", file=sys.stderr)
            return 1
        print(f"{args.out} matches the reference implementation")
        return 0
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(text)
    print(f"wrote {args.out} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
